package management.message;

public enum MngType {

    VERBINDUNGSAUFBAU_ANFRAGE,

    REGISTRIEREN,
    REGISTRIEREN_OK,
    REGISTRIEREN_NOK,

    ANMELDUNG,
    ANMELDUNG_OK,
    ANMELDUNG_NOK,

    ABMELDUNG,
    ABMELDUNG_OK,
    ABMELDUNG_NOK,

    CHATAUFFORDERUNG,
    CHATAUFFORDERUNG_OK,
    CHATAUFFORDERUNG_NOK,
    CHATAUFFORDERUNG_ABGELEHNT,

    CHATANFRAGE,
    CHATANFRAGE_OK,
    CHATANFRAGE_NOK,

    SEND_MESSAGE,
    SEND_MESSAGE_ACK,

    IP_ADRESSE,

    CLOSE_CHAT,
    DELETE_IP;
}